Repository cau-rubato/rubato-backend, pull requests merged in 2022-07, with the labels that each got.

#23 [chore/new-branch] Update the CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#26 [fix/domain_not_null] close #22
  src/main/java/org/rubatophil/www/api/domain/Account.java
  src/main/java/org/rubatophil/www/api/domain/Apply.java
  src/main/java/org/rubatophil/www/api/domain/ApplyCampaign.java
  src/main/java/org/rubatophil/www/api/domain/Budget.java
  src/main/java/org/rubatophil/www/api/domain/Department.java
  src/main/java/org/rubatophil/www/api/domain/Donate.java
  src/main/java/org/rubatophil/www/api/domain/FAQ.java
  src/main/java/org/rubatophil/www/api/domain/Manager.java
  src/main/java/org/rubatophil/www/api/domain/concert/Concert.java
  src/main/java/org/rubatophil/www/api/domain/concert/RegularConcert.java
  src/main/java/org/rubatophil/www/api/domain/mapping/ApplicantExperience.java
  src/main/java/org/rubatophil/www/api/domain/mapping/ConcertPamphlet.java
  src/main/java/org/rubatophil/www/api/domain/mapping/DonateBudget.java
  src/main/java/org/rubatophil/www/api/domain/mapping/MemberInstrument.java
  src/main/java/org/rubatophil/www/api/domain/mapping/concertMember/ClubConcertMember.java
  src/main/java/org/rubatophil/www/api/domain/mapping/concertMember/ConcertMember.java
  src/main/java/org/rubatophil/www/api/domain/mapping/concertMember/GuestConcertMember.java
  src/main/java/org/rubatophil/www/api/domain/member/Applicant.java
  src/main/java/org/rubatophil/www/api/domain/member/ClubMember.java
  src/main/java/org/rubatophil/www/api/domain/member/GuestMember.java
  src/main/java/org/rubatophil/www/api/domain/member/Member.java
  src/main/java/org/rubatophil/www/api/domain/member/Sponsor.java
  src/main/java/org/rubatophil/www/api/domain/type/Address.java
  src/main/java/org/rubatophil/www/api/domain/type/Experience.java
  src/main/java/org/rubatophil/www/api/domain/type/Location.java
Labels: enhancement

#27 [fix/rename_table] close #25
  src/main/java/org/rubatophil/www/api/domain/mapping/ApplicantExperience.java
Labels: refactor

#28 [fix/rename_field] close #24
  src/main/java/org/rubatophil/www/api/domain/type/Experience.java
Labels: enhancement

#31 [fix/domain_abstract_class] close #30
  src/main/java/org/rubatophil/www/api/domain/concert/Concert.java
  src/main/java/org/rubatophil/www/api/domain/mapping/concertMember/ConcertMember.java
  src/main/java/org/rubatophil/www/api/domain/member/Member.java
Labels: enhancement

#33 [feature/pieces_entity] close #32
  src/main/java/org/rubatophil/www/api/domain/Composer.java
  src/main/java/org/rubatophil/www/api/domain/Piece.java
  src/main/java/org/rubatophil/www/api/domain/concert/Concert.java
  src/main/java/org/rubatophil/www/api/domain/mapping/ConcertPiece.java
Labels: enhancement

#42 [fix/concert_domain] close #29
  src/main/java/org/rubatophil/www/api/domain/Account.java
  src/main/java/org/rubatophil/www/api/domain/Composer.java
  src/main/java/org/rubatophil/www/api/domain/Department.java
  src/main/java/org/rubatophil/www/api/domain/Piece.java
  src/main/java/org/rubatophil/www/api/domain/concert/Concert.java
  src/main/java/org/rubatophil/www/api/domain/concert/RegularConcert.java
  src/main/java/org/rubatophil/www/api/domain/mapping/ConcertPamphlet.java
  src/main/java/org/rubatophil/www/api/domain/mapping/concertMember/ClubConcertMember.java
  src/main/java/org/rubatophil/www/api/domain/mapping/concertMember/ConcertMember.java
  src/main/java/org/rubatophil/www/api/domain/mapping/concertMember/GuestConcertMember.java
  src/main/java/org/rubatophil/www/api/domain/mapping/concertPiece/ConcertPiece.java
  src/main/java/org/rubatophil/www/api/domain/mapping/concertPiece/RegularConcertPiece.java
  src/main/java/org/rubatophil/www/api/domain/member/ClubMember.java
  src/main/java/org/rubatophil/www/api/domain/member/GuestMember.java
  src/main/java/org/rubatophil/www/api/domain/member/Member.java
  src/main/java/org/rubatophil/www/api/domain/type/Address.java
  src/main/java/org/rubatophil/www/api/domain/type/Location.java
  src/main/java/org/rubatophil/www/api/domain/type/RegularConcertSection.java
  src/test/java/org/rubatophil/www/api/domain/concert/ConcertTest.java
  src/test/java/org/rubatophil/www/api/domain/concert/RegularConcertTest.java
Labels: enhancement, fix

#43 [fix/faq_entity] close #35
  src/main/java/org/rubatophil/www/api/domain/FAQ.java
  src/test/java/org/rubatophil/www/api/domain/FAQTest.java
  src/test/java/org/rubatophil/www/api/repository/FAQRepositoryTest.java
Labels: enhancement, fix

#44 [fix/concert_domain] close #29
  src/test/java/org/rubatophil/www/api/domain/concert/ConcertTest.java
  src/test/java/org/rubatophil/www/api/domain/concert/RegularConcertTest.java
Labels: enhancement, fix

#45 [fix/concert_domain] close #29
  src/test/java/org/rubatophil/www/api/domain/concert/ConcertTest.java
  src/test/java/org/rubatophil/www/api/domain/concert/RegularConcertTest.java
Labels: enhancement, fix

#46 [fix/member_domain] close #36 #37 #40 #41
  src/main/java/org/rubatophil/www/api/domain/Account.java
  src/main/java/org/rubatophil/www/api/domain/Department.java
  src/main/java/org/rubatophil/www/api/domain/Donate.java
  src/main/java/org/rubatophil/www/api/domain/Manager.java
  src/main/java/org/rubatophil/www/api/domain/mapping/ApplicantExperience.java
  src/main/java/org/rubatophil/www/api/domain/mapping/MemberInstrument.java
  src/main/java/org/rubatophil/www/api/domain/mapping/concertMember/ClubConcertMember.java
  src/main/java/org/rubatophil/www/api/domain/mapping/concertMember/ConcertMember.java
  src/main/java/org/rubatophil/www/api/domain/mapping/concertMember/GuestConcertMember.java
  src/main/java/org/rubatophil/www/api/domain/member/Applicant.java
  src/main/java/org/rubatophil/www/api/domain/member/ClubMember.java
  src/main/java/org/rubatophil/www/api/domain/member/GuestMember.java
  src/main/java/org/rubatophil/www/api/domain/member/Member.java
  src/main/java/org/rubatophil/www/api/domain/member/Sponsor.java
  src/main/java/org/rubatophil/www/api/domain/type/Experience.java
  src/test/java/org/rubatophil/www/api/domain/AccountTest.java
  src/test/java/org/rubatophil/www/api/domain/DepartmentTest.java
  src/test/java/org/rubatophil/www/api/domain/FAQTest.java
  src/test/java/org/rubatophil/www/api/domain/ManagerTest.java
  src/test/java/org/rubatophil/www/api/domain/concert/ConcertTest.java
  src/test/java/org/rubatophil/www/api/domain/concert/RegularConcertTest.java
  src/test/java/org/rubatophil/www/api/domain/member/ApplicantTest.java
  src/test/java/org/rubatophil/www/api/domain/member/ClubMemberTest.java
  src/test/java/org/rubatophil/www/api/domain/member/GuestMemberTest.java
  src/test/java/org/rubatophil/www/api/domain/member/MemberTest.java
  src/test/java/org/rubatophil/www/api/domain/member/SponsorTest.java
Labels: enhancement, fix

#47 [fix/piece_entity] close #38
  src/main/java/org/rubatophil/www/api/domain/Composer.java
  src/main/java/org/rubatophil/www/api/domain/Piece.java
  src/main/java/org/rubatophil/www/api/domain/concert/RegularConcert.java
  src/main/java/org/rubatophil/www/api/domain/mapping/concertPiece/ConcertPiece.java
  src/main/java/org/rubatophil/www/api/domain/mapping/concertPiece/RegularConcertPiece.java
  src/test/java/org/rubatophil/www/api/domain/ComposerTest.java
  src/test/java/org/rubatophil/www/api/domain/PieceTest.java
  src/test/java/org/rubatophil/www/api/domain/concert/RegularConcertTest.java
Labels: enhancement, fix

#49 [fix/donate_domain] close #39
  src/main/java/org/rubatophil/www/api/domain/Budget.java
  src/main/java/org/rubatophil/www/api/domain/Donate.java
  src/main/java/org/rubatophil/www/api/domain/mapping/DonateBudget.java
  src/test/java/org/rubatophil/www/api/domain/BudgetTest.java
  src/test/java/org/rubatophil/www/api/domain/DonateTest.java
Labels: enhancement, fix

#51 [ops/actions_unit_test] close #50
  .github/workflows/gradle.yml
Labels: ops, fix

#55 [ops/actions_unit_test] close #54
  .github/workflows/gradle.yml
Labels: ops

#56 [feature/faq] close #7
  src/main/java/org/rubatophil/www/api/controller/FAQController.java
  src/main/java/org/rubatophil/www/api/request/NewFAQ.java
  src/main/java/org/rubatophil/www/api/response/faq/FAQResponse.java
  src/main/java/org/rubatophil/www/api/service/FAQService.java
  src/test/java/org/rubatophil/www/api/controller/ApplyControllerTest.java
  src/test/java/org/rubatophil/www/api/controller/ConcertControllerTest.java
  src/test/java/org/rubatophil/www/api/controller/DonateControllerTest.java
  src/test/java/org/rubatophil/www/api/controller/FAQControllerTest.java
  src/test/java/org/rubatophil/www/api/controller/MemberControllerTest.java
  src/test/java/org/rubatophil/www/api/service/FAQServiceTest.java
Labels: enhancement

#57 [feature/faq] Merge the feature/faq to develop
  src/main/java/org/rubatophil/www/api/controller/FAQController.java
  src/main/java/org/rubatophil/www/api/request/NewFAQ.java
  src/main/java/org/rubatophil/www/api/response/faq/FAQResponse.java
  src/main/java/org/rubatophil/www/api/service/FAQService.java
  src/test/java/org/rubatophil/www/api/controller/ApplyControllerTest.java
  src/test/java/org/rubatophil/www/api/controller/ConcertControllerTest.java
  src/test/java/org/rubatophil/www/api/controller/DonateControllerTest.java
  src/test/java/org/rubatophil/www/api/controller/FAQControllerTest.java
  src/test/java/org/rubatophil/www/api/controller/MemberControllerTest.java
  src/test/java/org/rubatophil/www/api/service/FAQServiceTest.java
Labels: enhancement

#59 [feature/member] close #14
  src/main/java/org/rubatophil/www/api/controller/ClubMemberController.java
  src/main/java/org/rubatophil/www/api/controller/ConcertController.java
  src/main/java/org/rubatophil/www/api/controller/ManagerController.java
  src/main/java/org/rubatophil/www/api/controller/MemberController.java
  src/main/java/org/rubatophil/www/api/domain/mapping/MemberInstrument.java
  src/main/java/org/rubatophil/www/api/domain/member/Applicant.java
  src/main/java/org/rubatophil/www/api/domain/member/ClubMember.java
  src/main/java/org/rubatophil/www/api/domain/member/GuestMember.java
  src/main/java/org/rubatophil/www/api/domain/member/Member.java
  src/main/java/org/rubatophil/www/api/domain/member/Sponsor.java
  src/main/java/org/rubatophil/www/api/repository/DepartmentRepository.java
  src/main/java/org/rubatophil/www/api/repository/ManagerRepository.java
  src/main/java/org/rubatophil/www/api/repository/mapping/MemberInstrumentRepository.java
  src/main/java/org/rubatophil/www/api/repository/member/ApplicantRepository.java
  src/main/java/org/rubatophil/www/api/repository/member/ClubMemberRepository.java
  src/main/java/org/rubatophil/www/api/repository/member/GuestMemberRepository.java
  src/main/java/org/rubatophil/www/api/repository/member/MemberRepository.java
  src/main/java/org/rubatophil/www/api/repository/member/SponsorRepository.java
  src/main/java/org/rubatophil/www/api/request/NewManager.java
  src/main/java/org/rubatophil/www/api/request/member/NewClubMember.java
  src/main/java/org/rubatophil/www/api/response/ManagerResponse.java
  src/main/java/org/rubatophil/www/api/response/member/ClubMemberResponse.java
  src/main/java/org/rubatophil/www/api/response/member/MemberResponse.java
  src/main/java/org/rubatophil/www/api/service/ManagerService.java
  src/main/java/org/rubatophil/www/api/service/member/ClubMemberService.java
  src/test/java/org/rubatophil/www/api/controller/ClubMemberControllerTest.java
  src/test/java/org/rubatophil/www/api/controller/ManagerControllerTest.java
  src/test/java/org/rubatophil/www/api/controller/MemberControllerTest.java
  src/test/java/org/rubatophil/www/api/service/ManagerServiceTest.java
  src/test/java/org/rubatophil/www/api/service/member/ClubMemberServiceTest.java
Labels: enhancement

#60 [feature/faq] close #7
  src/main/java/org/rubatophil/www/api/controller/FAQController.java
  src/main/java/org/rubatophil/www/api/service/FAQService.java
  src/test/java/org/rubatophil/www/api/controller/DonateControllerTest.java
  src/test/java/org/rubatophil/www/api/controller/FAQControllerTest.java
Labels: enhancement

#62 [feature/member] Merge feature/member to develop
  src/main/java/org/rubatophil/www/api/controller/ClubMemberController.java
  src/main/java/org/rubatophil/www/api/controller/ConcertController.java
  src/main/java/org/rubatophil/www/api/controller/ManagerController.java
  src/main/java/org/rubatophil/www/api/controller/MemberController.java
  src/main/java/org/rubatophil/www/api/domain/mapping/MemberInstrument.java
  src/main/java/org/rubatophil/www/api/domain/member/Applicant.java
  src/main/java/org/rubatophil/www/api/domain/member/ClubMember.java
  src/main/java/org/rubatophil/www/api/domain/member/GuestMember.java
  src/main/java/org/rubatophil/www/api/domain/member/Member.java
  src/main/java/org/rubatophil/www/api/domain/member/Sponsor.java
  src/main/java/org/rubatophil/www/api/repository/DepartmentRepository.java
  src/main/java/org/rubatophil/www/api/repository/ManagerRepository.java
  src/main/java/org/rubatophil/www/api/repository/mapping/MemberInstrumentRepository.java
  src/main/java/org/rubatophil/www/api/repository/member/ApplicantRepository.java
  src/main/java/org/rubatophil/www/api/repository/member/ClubMemberRepository.java
  src/main/java/org/rubatophil/www/api/repository/member/GuestMemberRepository.java
  src/main/java/org/rubatophil/www/api/repository/member/MemberRepository.java
  src/main/java/org/rubatophil/www/api/repository/member/SponsorRepository.java
  src/main/java/org/rubatophil/www/api/request/NewManager.java
  src/main/java/org/rubatophil/www/api/request/member/NewClubMember.java
  src/main/java/org/rubatophil/www/api/response/ManagerResponse.java
  src/main/java/org/rubatophil/www/api/response/member/ClubMemberResponse.java
  src/main/java/org/rubatophil/www/api/response/member/MemberResponse.java
  src/main/java/org/rubatophil/www/api/service/ManagerService.java
  src/main/java/org/rubatophil/www/api/service/member/ClubMemberService.java
  src/test/java/org/rubatophil/www/api/controller/ClubMemberControllerTest.java
  src/test/java/org/rubatophil/www/api/controller/ManagerControllerTest.java
  src/test/java/org/rubatophil/www/api/controller/MemberControllerTest.java
  src/test/java/org/rubatophil/www/api/service/ManagerServiceTest.java
  src/test/java/org/rubatophil/www/api/service/member/ClubMemberServiceTest.java
Labels: enhancement
